aliev/aioauth

- src/aioauth/grant_type.py
- tests/test_flow.py
- tests/test_grant_type.py
Hi, thank you for your library.
I found a bug though. When refreshing a token the resulting scope should be 
- the scope of the previous token, if no scope was given OR
- a scope that doesn't have a bigger scope than the previous token
see https://www.oauth.com/oauth2-servers/making-authenticated-requests/refreshing-an-access-token/
> Bugfix for refresh token scope

- src/aioauth/grant_type.py
- src/aioauth/server.py
- tests/test_endpoint.py
- tests/test_grant_type.py
Fixed a bug that did not take into account the `token.revoked` in `create_token_introspection_response` method and `RefreshTokenGrantType` class.
> Added revoked tokens handler

- src/aioauth/base/database.py
- src/aioauth/grant_type.py
- src/aioauth/models.py
- src/aioauth/server.py
- tests/classes.py
- tests/test_db.py
E.g. token was renamed to access_token in `get_token` method.
> Fixed confusing naming in methods of BaseDB

- src/aioauth/grant_type.py
- src/aioauth/requests.py
- tests/test_flow.py
- tests/utils.py
client_id and client_secret can also be given via POST data. So added client_id and client_secret to Post namedtuple and trying to retrieve them via POST first. Auth Header if they were not found.
https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/
> Allow Credentials in POST

- README.md
- src/aioauth/base/database.py
- tests/classes.py
- tests/test_db.py
Hello, I was wondering if you'd be willing to accept this PR. I thought the generation of the `Token` namedtuple and the `AuthorizationCode` should not be part of the db interface, when I started with it I was a bit confused.
Now for a user, implementing the interface of `BaseDB` is just about the database.
My current implementation isolates the "save" part, a bit similar to [rest_framework mixins](https://github.com/encode/django-rest-framework/blob/master/rest_framework/mixins.py#L19)
I was also thinking about exposing the in-memory db as part of the library instead of the test, this would also help newcomers to test the library out. 
Let me know what you think.
Regards!
> refactor: move some business logic out of the db class

- README.md
- aioauth/requests.py
- aioauth/responses.py
- aioauth/server.py
- aioauth/types.py
- aioauth/utils.py
- tests/test_endpoint.py
- tests/test_flow.py
- tests/test_request_validator.py
- tests/utils.py
As part of the OpenID implementation, the ability to specify response_mode has been added.
You can read [here](https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#ResponseModes) more information about `response_mode`
Additional changes:
`Response.content` now returns a dictionary (empty content returns empty dictionary).
This was done so that the user of the library does not have to manually convert the object into a dictionary.
> Implemented response_mode for OpenID

- setup.cfg
In order to get rid of this warning:
```
PytestDeprecationWarning: The --strict option is deprecated, use --strict-markers instead.
self.issue_config_time_warning(
```
`--strict` option was replaced to `--strict-markers`
> fix: replaced --stric to --strict-markers in pytest options

- aioauth/collections.py
- aioauth/errors.py
- aioauth/grant_type.py
- aioauth/models.py
- aioauth/requests.py
- aioauth/response_type.py
- aioauth/server.py
- aioauth/storage.py
- aioauth/types.py
- aioauth/utils.py
- docs/source/sections/examples/fastapi.rst
- setup.py
- tests/classes.py
- tests/conftest.py
- tests/test_db.py
- tests/test_endpoint.py
- tests/test_flow.py
- tests/test_grant_type.py
- tests/test_request_validator.py
- tests/test_utils.py
- tests/utils.py
see the issue #63
while inheriting from models (Token, Client, AuthorizationCode), and using them in aioauth, mypy throws an error like:
```
error: Argument 1 of "create_authorization_code" is incompatible with supertype "BaseStorage"; supertype defines the argument type as "Request"
```
this PR fixes the above bug by adding additional `TToken`, `TClient` and `TAuthorizationCode` parameters to the `BaseModel` generic.
usage example:
```python
from dataclasses import dataclass
from aioauth_fastapi.router import get_oauth2_router
from aioauth.storage import BaseStorage
from aioauth.requests import BaseRequest
from aioauth.models import AuthorizationCode, Client, Token
from aioauth.config import Settings
from aioauth.server import AuthorizationServer
from fastapi import FastAPI
app = …
```
> fix: mypy errors on custom models

- aioauth/grant_type.py
During Authorization Code Flow the Token must be issued using the scope which the user approved in the Authorization Code. Currently the client can specify a different scope in the `/token` request and get a Token with scopes which were not approved.
> Use scope from authorization code when issuing token

- aioauth/errors.py
- aioauth/grant_type.py
- aioauth/response_type.py
- aioauth/server.py
- aioauth/utils.py
- tests/test_endpoint.py
- tests/test_request_validator.py
- tests/utils.py
The spec defines that most errors to `/authorize` should be returned to the redirect URI with `error` and `error_description` query params:
If the resource owner denies the access request or if the request
fails for reasons other than a missing or invalid redirection URI,
the authorization server informs the client by adding the following
parameters to the query component of the redirection URI using the
"application/x-www-form-urlencoded" format, per Appendix B:
Add `InvalidRedirectURIError` and use `InvalidClientError` for all `client_id` errors since these should not redirect. Update
`catch_errors_and_unavailability` to optionally return errors as redirects.
> Return most /authorize errors as a redirect

- aioauth/server.py
- aioauth/utils.py
The `catch_errors_and_unavailability` decorator was extended with a `redirect_on_exc` parameter to allow specifying a list of exceptions without changing the code of the decorator itself. The `redirect_on` argument has been removed.
> fix: catch_errors_and_unavailability redirect argument

- aioauth/grant_type.py
- aioauth/server.py
- tests/test_endpoint.py
- tests/test_flow.py
- tests/test_request_validator.py
- tests/utils.py
It could be that I'm doing something wrong, but if I attempt to exchange an authorization code for an access token and I don't supply some kind of dummy `client_secret`, then I get an `InvalidClientError`. If I supply a blank `client_secret`, I don't have a problem.
Relevant stacktrace is:
```
File ".../aioauth/server.py", line 256, in create_token_response
client_id, client_secret = self.get_client_credentials(request)
File ".../aioauth/server.py", line 216, in get_client_credentials
raise InvalidClientError[TRequest](
```
I think the code I've suggested solves the problem, badly, so I'm open to other ideas. I don't love that it hardcodes a check for `request.post.grant_type != "authorization_code"` because it doesn't solve the problem for other grant types and makes the library harder …
> Exchanging an authorization code for an access token needs no client_secret

- aioauth/errors.py
- aioauth/grant_type.py
- aioauth/response_type.py
- aioauth/server.py
- aioauth/types.py
For `ServerError` class the `ErrorType` value was `temporarily_unavailable`, it was replaced with `server_error` value.
Each attribute of error classes now has `ErrorType` type.
For `Literal`'s using the `get_args` in order to get the literal's value instead of hard coded strings.
> fix: type hinting refactoring and small bugfix

- aioauth/errors.py
- aioauth/grant_type.py
- aioauth/server.py
- aioauth/utils.py
- tests/test_flow.py
- tests/utils.py
Believe it or not, this is the beginning of working to make it so the password grant doesn't require a `client_secret`.
In broad strokes, this aims to make the setting of the `WWW-Authenticate` header the responsibility of the `InvalidClientError` instead of being the responsibility of the `get_client_credentials` function.
EDIT: I was going to make `client_secret` optional for the password grant in another PR, but it doesn't seem like there's enough extra code required to warrant that. So this now includes logic to make it so the password grant type doesn't require a `client_secret`. Viewing the changes by commit may help disentangle things.
> A client_secret is not required for the password grant type

- aioauth/server.py
- pytest.ini
- tests/conftest.py
- tests/test_flow.py
I realized that some of the tests I'd changed/added should have failed when a client with a client_secret tried to use the password grant without their client_secret. This fixes the related bug and the tests that should have been broken.
Not sure if there's an easier way to build a server with custom settings, but I thought this approach was pretty clean.
> A client must use their client_secret if they have one

- aioauth/server.py
- tests/test_flow.py
- tests/test_request_validator.py
I believe this should fix https://github.com/aliev/aioauth/issues/81.
Not sure how I messed this one up. The spec is pretty clear that, regardless of grant type, a client with a secret must authenticate with the secret:
> If the client type is confidential or the client was issued client credentials (or assigned other authentication requirements), the client MUST authenticate with the authorization server as described in Section 3.2.1.
Disclaimer: I just fixed existing tests to pass. I didn't add new tests that are needed. There's a bunch of refactoring I want to do to make it possible to test different `client_secret` scenarios cleanly without repeating a lot of code. I started that [over here](https://github.com/aliev/aioauth/commit/133d77389fd56379deac91e7b95bb900069e7ac4), but still …
> Fix bug preventing some grant types from getting client_secret

- aioauth/oidc/core/requests.py
- setup.py
- tests/conftest.py
- tests/oidc/core/test_flow.py
The [OpenID Connect Core spec](https://openid.net/specs/openid-connect-core-1_0.html) defines [an extension to the authorization code grant type that allows that grant type to take an optional `prompt`](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) query parameter that allows the client to have more control over how the auth server handles an authorization code request in scenarios where the user is not signed in or has not consented to all the scopes.
I think the handling of the `prompt` query argument is the responsibility of whomever is using this library, but I wonder if you'd be open to adding some support for the `prompt` query argument to this library. I tried to handle `prompt` without getting this library involved, but [`starlette`'s `QueryParams` class is …
> Allow OIDC prompt query param

- aioauth/errors.py
- aioauth/server.py
- aioauth/storage.py
- aioauth/types.py
- tests/classes.py
- tests/test_endpoint.py
RFC 7009: OAuth 2.0 Token Revocation
https://datatracker.ietf.org/doc/html/rfc7009
> Implement token revocation endpoint

- aioauth/errors.py
- tests/utils.py
> fix: invalid_client response is missing application/json content-type

- aioauth/server.py
The introspection response currently returns as `token_type` the value of the `token_type_hint` parameter (defaulted to "refresh_token"). However, [RFC7662, Section 2.2](https://www.rfc-editor.org/rfc/rfc7662#section-2.2) prescribes this to be the same kind of `token_type` as in the responses from the token endpoint (which is `"Bearer"` by default), which is the one stored as part of the token's `TToken` instance.
> fix: return correct `toke_type` in introspection

- aioauth/oidc/core/requests.py
- tests/utils.py
This adds a new OIDC BaseRequest class which is generic on the User type, unlike the existing OIDC Request class which hardcodes the User type to Any. This allows you to create a subclass of BaseRequest with a particular User type, just like you can do with the non-OIDC version of the BaseRequest class.
This is the same change as in #95 but with some extra commits removed that were accidentally included in the other PR. Sorry about that
> Make User generic in OIDC Request class

- aioauth/errors.py
- aioauth/response_type.py
- aioauth/server.py
- aioauth/utils.py
- tests/utils.py
The spec states that when redirecting back to the client after an authorization request error, the state parameter should be included if it was present in the request:
>   state
>         REQUIRED if a "state" parameter was present in the client
>         authorization request.  The exact value received from the
>         client.
https://www.rfc-editor.org/rfc/rfc6749.html#section-4.1.2.1
This adds the state parameter to redirect responses for authorization request errors. Additionally this modifies the `check_query_values` test utility function to inject the state into the expected redirect URI, so that the behaviour is tested.
Before the change:
```
FAILED tests/test_flow.py::test_authorization_code_flow - AssertionError: Response(content={}, status_code=<HTTPStatus.FOUND: 302>, …
```
> Add state parameter to authorization error redirects

- aioauth/server.py
- tests/test_endpoint.py
This PR fixes two issues I noticed with the token introspection and revocation endpoints:
- Neither endpoint actually checks to make sure that the client secret provided is actually correct, only that one is provided.
- The revoke token endpoint fails if a client secret is not provided, even if the client is a public client that doesn't have a client secret. The RFC 7009 specification seems to imply that public clients should be allowed to revoke tokens in section 2.1 "Revocation Request":
>   The authorization server first validates the client credentials (in
>   case of a confidential client) and then verifies whether the token
>   was issued to the client making the revocation request.  If this
>   validation fails, the request is refused and the client is informed
>   of the error by …
> Fix token introspection and revocation authentication checks

- pyproject.toml
fixes a pre-commit and github action error related to mypy's dependency scanning for the new fastapi example.
based on discussion https://github.com/aliev/aioauth/pull/106#issuecomment-2525055518 and https://github.com/aliev/aioauth/pull/106#issuecomment-2525180878
> fix: avoid mypy dependency resolution error within example on pre-commit check

- aioauth/config.py
- aioauth/response_type.py
- aioauth/responses.py
- aioauth/server.py
- aioauth/storage.py
- tests/test_flow.py
Solution proposal for issues: #98.
This commit includes additional logic to make the generation of refresh tokens optional in implicit grant flows so that this package becomes strictly compliant with the OAuth 2.0 specification in section 4.2. To see further information, please refer to issue #98.
To not break backward compatibility, this new option has been included as an new optional setting flag, `ISSUE_REFRESH_TOKEN_IMPLICIT_GRANT`, that when set to `False`, it deactivates the refresh token generation in implicit flows.
> Optional refresh token in implicit grant

- aioauth/errors.py
- aioauth/types.py
- aioauth/utils.py
features:
- adds support for `access_denied` error in [oauth2 rfc](https://datatracker.ietf.org/doc/html/rfc6749)
- allows apis to implement their own custom exceptions (e.g. scope permission approval pages)
example:
```python3
import json
from fastapi import FastAPI, Query, Request, Response
from aioauth.server import AuthorizationServer
from aioauth.errors import AccessDeniedError, OAuth2Error
from aioauth.storage import BaseStorage
from aioauth.utils import build_error_response
from aioauth.responses import Response as OAuthResponse
app     = FastAPI()
storage = BaseStorage()
server  = AuthorizationServer(storage)
def to_response(response: OAuthResponse) -> Response:
"""
convert aioauth oauth2 response into fastapi response
"""
return Response(
content=json.dumps(response.content), …
```
> feat: support for building custom error-responses

- aioauth/storage.py
- examples/shared/storage.py
- tests/classes.py
This PR removes the use of `Unpack` and `TypedDict` in favor of named parameters, as these introduce additional "hacks" to support older Python versions, making the code more complex.
Discussion thread: https://github.com/aliev/aioauth/pull/106#issuecomment-2484151019# Please enter the commit message for your changes. Lines starting
> feat: refactor storage methods to use keyword-only arguments for clarity

- aioauth/response_type.py
Make the handling of `response_type` more explicit by removing the type ignore and adding an assertion to ensure it is not empty or None.
> Remove type ignore for response_type in authorization response

- aioauth/response_type.py
- aioauth/server.py
- examples/fastapi_example.py
addresses: https://github.com/aliev/aioauth/issues/101
This is only a quick edit for a potential solution.
I'd be happy to discuss strategy here or in the related issue.
> feat: separate authcode validation and response generation
